POST http://localhost:8080/api/ktp
Content-Type: application/json

{
  "nomorKtp": "99999999",
  "namaLengkap": "Neira",
  "alamat": "Jakarta",
  "tanggalLahir": "2000-01-01",
  "jenisKelamin": "Perempuan"
}